version: '3'

services:
  balancer:
    container_name: 'balancer'
    image: nginx
    volumes:
      - ./balancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    networks:
      - balancer

  web1:
    container_name: 'web1'
    build:
        context: "./docker/web1"
        dockerfile: "Dockerfile"
    volumes:
      - ./web1:/var/www/html
    ports:
      - 7000:80
    networks:
      - balancer

  web2:
    container_name: 'web2'
    build:
        context: "./docker/web2"
        dockerfile: "Dockerfile"
    volumes:
      - ./web2:/var/www/html
    ports:
      - 7001:80
    networks:
      - balancer

networks:
  balancer:
    driver: "bridge"
