version: '3'

services:
  proxy:
    image: nginx
    volumes:
      - ./proxy/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    networks:
      balancer:
        ipv4_address: 192.168.192.1

  web1:
    image: nginx
    container_name: 'web1'
    volumes:
      - ./web1:/usr/share/nginx/html
    ports:
      - 7000:80
    networks:
      balancer:
        ipv4_address: 192.168.192.2

  web2:
    image: nginx
    container_name: 'web2'
    volumes:
      - ./web2:/usr/share/nginx/html
    ports:
      - 7001:80
    networks:
      balancer:
        ipv4_address: 192.168.192.3

networks:
  balancer:
    driver: bridge
    ipam:
      config:
      - subnet: 192.168.192.0/24
