version: '3'

services:
  balancer:
    container_name: 'balancer'
    image: nginx
    volumes:
      - ./balancer/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 8080:80
    networks:
      - balancer

  web1:
    image: nginx
    container_name: 'web1'
    volumes:
      - ./web1:/usr/share/nginx/html
    ports:
      - 7000:80
    networks:
      - balancer

  web2:
    image: nginx
    container_name: 'web2'
    volumes:
      - ./web2:/usr/share/nginx/html
    ports:
      - 7001:80
    networks:
      - balancer

networks:
  balancer:
    driver: "bridge"
